# Generated by Django 4.1.5 on 2023-01-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_cnab", models.FileField(upload_to="uploads")),
            ],
        ),
        migrations.CreateModel(
            name="CnabReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=1)),
                ("data", models.CharField(max_length=8)),
                ("valor", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.CharField(max_length=8)),
                ("dono_loja", models.CharField(max_length=14)),
                ("nome_loja", models.CharField(max_length=19)),
                (
                    "cnab_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnabs",
                        to="upload_cnab.uploadfile",
                    ),
                ),
            ],
        ),
    ]
